// ============ DATA ============
const deities = {
  ganesh: {
    name: 'श्री गणेश',
    english: 'Shri Ganesh',
    emoji: '🐘',
    color: '#FF6B00',
    desc: 'विघ्नहर्ता, प्रथम पूज्य',
    img: 'icons/ganesh.webp',
  },
  shiva: {
    name: 'श्री शिव',
    english: 'Shri Shiv',
    emoji: '🔱',
    color: '#4169E1',
    desc: 'महादेव, भोलेनाथ, संहारक',
    img: 'icons/shiv.webp',
  },
  durga: {
    name: 'श्री दुर्गा',
    english: 'Shri Durga',
    emoji: '🌸',
    color: '#FF1493',
    desc: 'आदिशक्ति, महामाया, सिंहवाहिनी',
    img: 'icons/durga.webp',
  },
  lakshmi: {
    name: 'श्री लक्ष्मी',
    english: 'Shri Lakshmi',
    emoji: '🪷',
    color: '#FFD700',
    desc: 'धनदात्री, कमलावासिनी, समृद्धि की देवी',
    img: 'icons/lakshmi.webp',
  },
  saraswati: {
    name: 'श्री सरस्वती',
    english: 'Shri Saraswati',
    emoji: '🎵',
    color: '#FFFFFF',
    desc: 'विद्यादायिनी, वागदेवी, वीणावादिनी',
    img: 'icons/saraswati.webp',
  },
  vishnu: {
    name: 'श्री विष्णु',
    english: 'Shri Vishnu',
    emoji: '✨',
    color: '#0080FF',
    desc: 'पालनहार, नारायण, जगत के पालक',
    img: 'icons/vishnu.webp',
  },
  ram: {
    name: 'श्री राम',
    english: 'Shri Ram',
    emoji: '🏹',
    color: '#00AA00',
    desc: 'मर्यादा पुरुषोत्तम, रघुकुल के भूषण',
    img: 'icons/ram.webp',
  },
  krishna: {
    name: 'श्री कृष्ण',
    english: 'Shri Krishna',
    emoji: '🪈',
    color: '#0000CD',
    desc: 'गोविन्द, मुरलीमनोहर, ब्रजबिहारी',
    img: 'icons/krishna.webp',
  },
  hanuman: {
    name: 'श्री हनुमान',
    english: 'Shri Hanuman',
    emoji: '🙏',
    color: '#FF4500',
    desc: 'पवनपुत्र, बजरंगबली, राम भक्त शिरोमणि',
    img: 'icons/hanuman.webp',
  },
  surya: {
    name: 'श्री सूर्य',
    english: 'Shri Surya',
    emoji: '☀️',
    color: '#FF8C00',
    desc: 'प्रत्यक्ष देव, जगत के नेत्र, ऊर्जा स्रोत',
    img: 'icons/surya.webp',
  },
  kali: {
    name: 'श्री काली',
    english: 'Shri Kali',
    emoji: '⚡',
    color: '#800080',
    desc: 'महाकाली, तारा, आद्यशक्ति की उग्र रूप',
    img: 'icons/kali.webp',
  },
  khatu_shyam: {
    name: 'श्री खाटू श्याम',
    english: 'Shri Khatu Shyam',
    emoji: '🏹',
    color: '#FF4500',
    desc: 'हारे का सहारा, मोर्वी नंदन, कलियुग के अवतारी',
    img: 'icons/khatu_shyam.webp',
  },
  shani: {
    name: 'श्री शनि देव',
    english: 'Shri Shani Dev',
    emoji: '⚖️',
    color: '#1a1a1a',
    desc: 'कर्म फल दाता, सूर्य पुत्र, न्याय के देवता',
    img: 'icons/shani.webp',
  },
  gopal: {
    name: 'श्री गोपाल',
    english: 'Shri Gopal',
    emoji: '🐄',
    color: '#5C6BC0',
    desc: 'बाल गोविंद, गोपालक, करुणामय',
    img: 'icons/gopal.webp',
  },
  brahma: {
    name: 'श्री ब्रह्मा',
    english: 'Shri Brahma',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'सृष्टिकर्ता, वेदज्ञ, चतुर्मुख',
    img: 'icons/brahma.webp',
  },
  bhairav: {
    name: 'श्री भैरव',
    english: 'Shri Bhairav',
    emoji: '🐕',
    color: '#37474F',
    desc: 'क्षेत्रपाल, रक्षक, उग्र करुणामय',
    img: 'icons/bhairav.webp',
  },
  batuk_bhairav: {
    name: 'श्री बटुक भैरव',
    english: 'Shri Batuk Bhairav',
    emoji: '🛡️',
    color: '#455A64',
    desc: 'बाल भैरव, त्वरित रक्षक',
    img: 'icons/batuk_bhairav.webp',
  },
  navgrah: {
    name: 'श्री नवग्रह',
    english: 'Shri Navgrah',
    emoji: '🪐',
    color: '#546E7A',
    desc: 'नौ ग्रहों का समष्टि पूजन',
    img: 'icons/navgrah.webp',
  },
  vishwakarma: {
    name: 'श्री विश्वकर्मा',
    english: 'Shri Vishwakarma',
    emoji: '🛠️',
    color: '#6D4C41',
    desc: 'देव शिल्पी, निर्माण देव',
    img: 'icons/vishwakarma.webp',
  },
  ravidas: {
    name: 'श्री रविदास',
    english: 'Shri Ravidas',
    emoji: '🙏',
    color: '#8D6E63',
    desc: 'भक्ति संत, समता संदेश',
    img: 'icons/ravidas.webp',
  },
  gorakh_nath: {
    name: 'श्री गोरख नाथ',
    english: 'Shri Gorakh Nath',
    emoji: '🧘',
    color: '#607D8B',
    desc: 'नाथ योग परंपरा के आचार्य',
    img: 'icons/gorakh_nath.webp',
  },
  jaharveer: {
    name: 'श्री जाहरवीर',
    english: 'Shri Jaharveer',
    emoji: '🏇',
    color: '#795548',
    desc: 'लोक रक्षक, वीर देव',
    img: 'icons/jaharveer.webp',
  },
  pretraj_sarkar: {
    name: 'श्री प्रेतराज सरकार',
    english: 'Shri Pretraj Sarkar',
    emoji: '🔥',
    color: '#4E342E',
    desc: 'नकारात्मक बाधा निवारक',
    img: 'icons/pretraj_sarkar.webp',
  },
  balaji: {
    name: 'श्री बालाजी',
    english: 'Shri Balaji',
    emoji: '🏹',
    color: '#8D6E63',
    desc: 'संकटमोचक पूज्य स्वरूप',
    img: 'icons/balaji.webp',
  },
  tirupati_balaji: {
    name: 'श्री तिरुपति बालाजी',
    english: 'Tirupati Bala Ji',
    emoji: '🌟',
    color: '#FFD54F',
    desc: 'श्री वेंकटेश्वर, विष्णु का पूज्य स्वरूप',
    img: 'icons/tirupati_balaji.webp',
  },
  sai: {
    name: 'श्री साईं',
    english: 'Shri Sai',
    emoji: '🕯️',
    color: '#9E9D24',
    desc: 'श्रद्धा और सबूरी के प्रतीक',
    img: 'icons/sai.webp',
  },
  giriraj: {
    name: 'श्री गिरिराज',
    english: 'Shri Giriraj',
    emoji: '⛰️',
    color: '#7CB342',
    desc: 'गोवर्धन स्वरूप, शरणदाता',
    img: 'icons/giriraj.webp',
  },
  mahavir: {
    name: 'श्री महावीर',
    english: 'Shri Mahavir',
    emoji: '🪷',
    color: '#26A69A',
    desc: 'अहिंसा, तप और सत्य के आदर्श',
    img: 'icons/mahavir.webp',
  },
  parshuram: {
    name: 'श्री परशुराम',
    english: 'Shri Parshuram',
    emoji: '🪓',
    color: '#5D4037',
    desc: 'विष्णु अवतार, धर्म रक्षक',
    img: 'icons/parshuram.webp',
  },
  ramdev: {
    name: 'श्री रामदेव',
    english: 'Shri Ramdev',
    emoji: '🐎',
    color: '#8E24AA',
    desc: 'लोकदेव, जनकल्याणकारी',
    img: 'icons/ramdev.webp',
  },
  pitar: {
    name: 'श्री पितर',
    english: 'Shri Pitar',
    emoji: '🕯',
    color: '#6D4C41',
    desc: 'पूर्वज पूजन, कुल आशीर्वाद',
    img: 'icons/pitar.webp',
  },
  baba_gangaram: {
    name: 'श्री बाबा गंगाराम',
    english: 'Shri Baba Gangaram',
    emoji: '🛕',
    color: '#6A1B9A',
    desc: 'लोक श्रद्धा के पूज्य संत',
    img: 'icons/baba_gangaram.webp',
  },
  vindhyeshwari: {
    name: 'श्री विन्ध्येश्वरी',
    english: 'Shri Vindhyeshwari',
    emoji: '🌺',
    color: '#D81B60',
    desc: 'विंध्यवासिनी माता का स्वरूप',
    img: 'icons/vindhyeshwari.webp',
  },
  mahalakshmi: {
    name: 'श्री महालक्ष्मी',
    english: 'Shri Mahalakshmi',
    emoji: '💰',
    color: '#F9A825',
    desc: 'ऐश्वर्य, सौभाग्य, मंगलमयी',
    img: 'icons/mahalakshmi.webp',
  },
  gayatri: {
    name: 'श्री गायत्री',
    english: 'Shri Gayatri',
    emoji: '📿',
    color: '#FF7043',
    desc: 'वेदमाता, बुद्धि प्रदायिनी',
    img: 'icons/gayatri.webp',
  },
  mahakali: {
    name: 'श्री महाकाली',
    english: 'Shri Mahakali',
    emoji: '⚔️',
    color: '#283593',
    desc: 'काल-विनाशिनी, अदम्य शक्ति',
    img: 'icons/mahakali.webp',
  },
  sheetla: {
    name: 'श्री शीतला',
    english: 'Shri Sheetla',
    emoji: '🧺',
    color: '#00ACC1',
    desc: 'आरोग्य दायिनी माता',
    img: 'icons/sheetla.webp',
  },
  radha: {
    name: 'श्री राधा',
    english: 'Shri Radha',
    emoji: '🌸',
    color: '#EC407A',
    desc: 'भक्ति और प्रेम की अधिष्ठात्री',
    img: 'icons/radha.webp',
  },
  tulsi: {
    name: 'श्री तुलसी',
    english: 'Shri Tulsi',
    emoji: '🌿',
    color: '#43A047',
    desc: 'पवित्रता, भक्ति और संरक्षण',
    img: 'icons/tulsi.webp',
  },
  vaishno_devi: {
    name: 'श्री वैष्णो देवी',
    english: 'Shri Vaishno Devi',
    emoji: '🛕',
    color: '#C2185B',
    desc: 'त्रिकुटा वासिनी, शक्ति स्वरूपा',
    img: 'icons/vaishno_devi.webp',
  },
  santoshi_maa: {
    name: 'श्री संतोषी माँ',
    english: 'Shri Santoshi Maa',
    emoji: '🍚',
    color: '#F06292',
    desc: 'संतोष, सुख और सरल भक्ति',
    img: 'icons/santoshi_maa.webp',
  },
  annapurna: {
    name: 'श्री अन्नपूर्णा',
    english: 'Shri Annapurna',
    emoji: '🍲',
    color: '#FF8F00',
    desc: 'अन्न, पोषण और करुणा की देवी',
    img: 'icons/annapurna.webp',
  },
  parvati: {
    name: 'श्री पार्वती',
    english: 'Shri Parvati',
    emoji: '🪷',
    color: '#AD1457',
    desc: 'शिव की अर्धांगिनी, शक्ति और मातृत्व की देवी',
    img: 'icons/parvati.webp',
  },
  baglamukhi: {
    name: 'श्री बगलामुखी',
    english: 'Shri Baglamukhi',
    emoji: '🟡',
    color: '#FBC02D',
    desc: 'दशमहाविद्या, स्तंभन शक्ति',
    img: 'icons/baglamukhi.webp',
  },
  ganga: {
    name: 'श्री गंगा',
    english: 'Shri Ganga',
    emoji: '🌊',
    color: '#1E88E5',
    desc: 'पावन नदी, मोक्षदायिनी',
    img: 'icons/ganga.webp',
  },
  narmada: {
    name: 'श्री नर्मदा',
    english: 'Shri Narmada',
    emoji: '💧',
    color: '#039BE5',
    desc: 'रेवा माता, पुण्यदायिनी',
    img: 'icons/narmada.webp',
  },
  sharda: {
    name: 'श्री शारदा',
    english: 'Shri Sharda',
    emoji: '📖',
    color: '#5E35B1',
    desc: 'ज्ञान और वाणी का स्वरूप',
    img: 'icons/sharda.webp',
  },
  shakambhari: {
    name: 'श्री शाकम्भरी',
    english: 'Shri Shakambhari',
    emoji: '🥬',
    color: '#7CB342',
    desc: 'अन्न-वनस्पति पोषक देवी',
    img: 'icons/shakambhari.webp',
  },
  lalita_shakambhari: {
    name: 'श्री ललिता शाकम्भरी',
    english: 'Shri Lalita Shakambhari',
    emoji: '🌼',
    color: '#8BC34A',
    desc: 'ललिता और शाकम्भरी का संयुक्त भाव',
    img: 'icons/lalita_shakambhari.webp',
  },
  rani_sati: {
    name: 'श्री राणी सती',
    english: 'Shri Rani Sati',
    emoji: '🏵️',
    color: '#8E24AA',
    desc: 'लोक आस्था की पूज्य मातृशक्ति',
    img: 'icons/rani_sati.webp',
  },
};
